import { useState, useEffect, useCallback } from 'react'

export type Locale = 'en' | 'ko'

const STORAGE_KEY = 'ajy-locale'

function detectLocale(): Locale {
  const stored = localStorage.getItem(STORAGE_KEY)
  if (stored === 'en' || stored === 'ko') return stored
  return navigator.language.startsWith('ko') ? 'ko' : 'en'
}

export function useLocale() {
  const [locale, setLocaleState] = useState<Locale>(detectLocale)

  useEffect(() => {
    document.documentElement.lang = locale
  }, [locale])

  const setLocale = useCallback((l: Locale) => {
    setLocaleState(l)
    localStorage.setItem(STORAGE_KEY, l)
  }, [])

  const toggleLocale = useCallback(() => {
    setLocale(locale === 'ko' ? 'en' : 'ko')
  }, [locale, setLocale])

  const t = translations[locale]

  return { locale, setLocale, toggleLocale, t } as const
}

// ─── Translation strings ───

const translations = {
  en: {
    // Demo banner
    demoBannerTitle: 'Portfolio Demo Site',
    demoBannerText: 'No real charges. 3-day free trial — use card number',
    demoBannerCardSuffix: 'to test.',
    demoBannerClose: 'Close',

    // Hero
    heroTitle1: 'Find Your',
    heroTitle2: 'Perfect Fit',
    heroTitle3: 'with AI.',
    heroDesc:
      'AI-powered fashion styling software that generates personalized lookbooks based on your measurements and aesthetic preferences.',
    heroBtn: 'Get Started',

    // How it works
    howLabel: 'The Process',
    howTitle: 'How It Works',
    step1Title: '1. Input Body Data',
    step1Desc:
      'Share your height and weight metrics to help our AI understand your unique silhouette.',
    step2Title: '2. Upload Photo',
    step2Desc:
      'A simple full-body photo allows the AI to analyze your posture and skin undertones.',
    step3Title: '3. Receive AI Curation',
    step3Desc:
      'Our software instantly generates a personalized digital lookbook with fashion recommendations matched to you.',

    // Gallery
    galleryTitle: 'Curated For You',
    galleryLink: 'View Collection',

    // Footer
    footerDesc:
      'AI Fashion Styling Software. All style reports are automatically generated by AI and are intended as fashion reference material only. This service does not provide human consulting, medical advice, or health guidance.',
    footerTerms: 'Terms of Service',
    footerPrivacy: 'Privacy Policy',
    footerCopy: '\u00A9 2026 AJY Stylist. All rights reserved.',

    // Form
    formLabel: 'New Analysis',
    formTitle: 'Your Details',
    photoText: 'Add Photo',
    photoLabel: 'Please upload a full-body photo of yourself',
    genderLabel: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    heightLabel: 'Height',
    heightPlaceholder: 'e.g. 175',
    weightLabel: 'Weight',
    weightPlaceholder: 'e.g. 68',
    submitBtn: 'Start Free Trial & Get Style Analysis',
    getReportBtn: 'Get Style Report',
    loadingAnalysis: 'AI is analyzing...',
    loadingCheckout: 'Preparing subscription...',
    loadingSubscriptionCheck: 'Checking subscription...',
    paymentNote: '3-day free trial \u00B7 Subscription via Polar',
    subscriptionActive: 'Active Subscription',
    loginRequiredMsg: 'Please log in to get your style report.',

    // Report
    reportLabel: 'AI Analysis',
    reportTitle: 'Style Report',
    hairstyleTitle: 'AI Style Lookbook',
    saveBtn: 'Save Image',
    savingBtn: 'Saving...',
    shareBtn: 'Share',
    sharingBtn: 'Sharing...',
    disclaimer:
      'This report is AI-generated fashion reference material. It does not replace professional stylist advice and does not include health or medical guidance.',
    retryBtn: 'Analyze Again',
    homeBtn: 'Back to Home',
    shareTitle: 'AJY Stylist - My Style Report',
    shareText: 'Check out my AI-generated style report!',
    clipboardCopied: 'Link copied to clipboard!',
    emailPolicyNote: 'The report will be sent to the email address you enter at checkout. You can cancel your subscription anytime.',

    // Auth
    authLabel: 'Account',
    loginTitle: 'Log In',
    signupTitle: 'Create Account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    loginBtn: 'Log In',
    signupBtn: 'Sign Up',
    loginSubmitting: 'Logging in...',
    signupSubmitting: 'Creating account...',
    orDivider: 'or',
    googleBtn: 'Continue with Google',
    kakaoBtn: 'Continue with Kakao',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signupLink: 'Sign up',
    loginLink: 'Log in',
    logoutBtn: 'Logout',
    signupSuccess: 'Account created! Please check your email for a confirmation link.',
    authRequired: 'Please log in to proceed with the style analysis.',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Find Password',
    forgotPasswordDesc: 'Enter your registered email address. We will send you a password reset link.',
    forgotPasswordBtn: 'Send Reset Email',
    forgotPasswordSending: 'Sending...',
    forgotPasswordSent: 'Password reset email sent! Please check your inbox and click the link to set a new password.',
    backToLogin: '\u2190 Back to Login',
    resetPasswordTitle: 'Set New Password',
    resetPasswordDesc: 'Please enter your new password.',
    resetPasswordBtn: 'Set New Password',
    resetPasswordSuccess: 'Password changed successfully! Redirecting to home...',
    errorPasswordMismatch: 'Passwords do not match.',
    errorInvalidEmail: 'Please enter a valid email address.',
    errorPasswordTooShort: 'Password must be at least 8 characters.',
    errorPasswordWeak: 'Password must include uppercase, lowercase, number, and special character.',
    errorAuthGeneric: 'An authentication error occurred.',

    // Errors (client-side)
    errorAnalysis: 'An error occurred during analysis.',
    errorUnknown: 'An unknown error occurred.',
    errorCheckout: 'Failed to create payment session.',
    errorPayment: 'An error occurred during payment.',

    // My Page
    myPageLabel: 'Account',
    myPageTitle: 'My Page',
    myPageEmail: 'Email',
    myPageProvider: 'Login Method',
    myPageJoined: 'Member Since',
    myPageProviderEmail: 'Email',
    myPageProviderGoogle: 'Google',
    myPageProviderKakao: 'Kakao',
    myPagePasswordSection: 'Change Password',
    myPageNewPassword: 'New Password',
    myPageConfirmPassword: 'Confirm New Password',
    myPageSavePassword: 'Update Password',
    myPageSavingPassword: 'Updating...',
    myPagePasswordSuccess: 'Password updated successfully.',
    myPageOAuthPasswordNote: 'Password change is not available for social login accounts.',
    myPageDangerZone: 'Danger Zone',
    myPageDeleteAccountDesc: 'Permanently delete your account and all associated data. This action cannot be undone.',
    myPageDeleteAccount: 'Delete Account',
    myPageDeleteConfirmTitle: 'Delete Account',
    myPageDeleteConfirmText: 'This action is permanent and cannot be undone. All your data will be deleted.',
    myPageDeleteConfirmBtn: 'Delete My Account',
    myPageDeletingAccount: 'Deleting...',
    myPageDeleteCancel: 'Cancel',
    myPageDeleteError: 'Account deletion failed. Please contact support.',

    // Subscription management
    myPageSubscriptionSection: 'Subscription',
    myPageSubscriptionActive: 'Active',
    myPageSubscriptionCanceling: 'Cancels at period end',
    myPageSubscriptionNone: 'No active subscription',
    myPageSubscriptionActiveDesc: 'Your subscription is active. You have unlimited access to style analysis.',
    myPageSubscriptionCancelingDesc: 'Your subscription is set to cancel. Access continues until the end of the billing period.',
    myPageCancelSubscription: 'Cancel Subscription',
    myPageCancelSubscriptionConfirmTitle: 'Cancel Subscription?',
    myPageCancelSubscriptionConfirmText: 'Your subscription will remain active until the end of the current billing period. After that, you will lose access to style analysis.',
    myPageCancelSubscriptionConfirmBtn: 'Yes, Cancel',
    myPageCancellingSubscription: 'Cancelling...',
    myPageKeepSubscription: 'Keep Subscription',
    myPageCancelSubscriptionSuccess: 'Subscription cancelled. You can continue using the service until the end of the billing period.',
    myPageCancelSubscriptionError: 'Failed to cancel subscription. Please try again.',
  },
  ko: {
    // Demo banner
    demoBannerTitle: '포트폴리오 데모 사이트',
    demoBannerText: '실제 결제 없음. 3일 무료 체험 — 테스트 카드번호',
    demoBannerCardSuffix: '로 시작해보세요.',
    demoBannerClose: '닫기',

    // Hero
    heroTitle1: 'Find Your',
    heroTitle2: 'Perfect Fit',
    heroTitle3: 'with AI.',
    heroDesc:
      'AI 기반 패션 스타일링 소프트웨어가 당신의 체형과 취향에 맞는 맞춤 룩북을 자동으로 생성합니다.',
    heroBtn: '시작하기',

    // How it works
    howLabel: '프로세스',
    howTitle: '이용 방법',
    step1Title: '1. 체형 정보 입력',
    step1Desc:
      'AI가 당신의 실루엣을 이해할 수 있도록 키와 몸무게를 입력해주세요.',
    step2Title: '2. 사진 업로드',
    step2Desc:
      '전신 사진 한 장으로 AI가 자세와 피부 톤을 분석합니다.',
    step3Title: '3. AI 큐레이션 받기',
    step3Desc:
      '소프트웨어가 즉시 당신에게 맞는 맞춤형 디지털 룩북과 패션 추천을 생성합니다.',

    // Gallery
    galleryTitle: '맞춤 큐레이션',
    galleryLink: '컬렉션 보기',

    // Footer
    footerDesc:
      'AI 패션 스타일링 소프트웨어. 모든 스타일 보고서는 AI가 자동 생성한 패션 참고 자료입니다. 본 서비스는 전문 컨설팅, 의학적 조언 또는 건강 지도를 제공하지 않습니다.',
    footerTerms: '이용약관',
    footerPrivacy: '개인정보처리방침',
    footerCopy: '\u00A9 2026 AJY Stylist. All rights reserved.',

    // Form
    formLabel: '새 분석',
    formTitle: '상세 정보',
    photoText: '사진 추가',
    photoLabel: '본인 전신 사진을 올려주세요',
    genderLabel: '성별',
    genderMale: '남성',
    genderFemale: '여성',
    heightLabel: '키',
    heightPlaceholder: '예: 175',
    weightLabel: '몸무게',
    weightPlaceholder: '예: 68',
    submitBtn: '무료 체험 시작 후 스타일 분석 받기',
    getReportBtn: '스타일 리포트 받기',
    loadingAnalysis: 'AI가 분석 중입니다...',
    loadingCheckout: '구독 준비 중...',
    loadingSubscriptionCheck: '구독 확인 중...',
    paymentNote: '3일 무료 체험 · Polar 구독 결제',
    subscriptionActive: '구독 활성 중',
    loginRequiredMsg: '스타일 리포트를 받으려면 로그인해주세요.',

    // Report
    reportLabel: 'AI 분석',
    reportTitle: '스타일 리포트',
    hairstyleTitle: 'AI 스타일 룩북',
    saveBtn: '이미지 저장',
    savingBtn: '저장 중...',
    shareBtn: '공유하기',
    sharingBtn: '공유 중...',
    disclaimer:
      '본 보고서는 AI 소프트웨어가 자동 생성한 패션 참고 자료입니다. 전문 스타일리스트의 조언을 대체하지 않으며, 건강 또는 의학적 조언을 포함하지 않습니다.',
    retryBtn: '다시 분석하기',
    homeBtn: '홈으로 돌아가기',
    shareTitle: 'AJY Stylist - My Style Report',
    shareText: 'AI가 분석한 나만의 스타일 리포트를 확인해보세요!',
    clipboardCopied: '링크가 클립보드에 복사되었습니다!',
    emailPolicyNote: '리포트는 구독 시 입력한 이메일 주소로 전송됩니다. 구독은 언제든지 취소할 수 있습니다.',

    // Auth
    authLabel: '계정',
    loginTitle: '로그인',
    signupTitle: '회원가입',
    emailLabel: '이메일',
    passwordLabel: '비밀번호',
    confirmPasswordLabel: '비밀번호 확인',
    loginBtn: '로그인',
    signupBtn: '회원가입',
    loginSubmitting: '로그인 중...',
    signupSubmitting: '계정 생성 중...',
    orDivider: '또는',
    googleBtn: 'Google로 계속하기',
    kakaoBtn: 'Kakao로 계속하기',
    noAccount: '계정이 없으신가요?',
    hasAccount: '이미 계정이 있으신가요?',
    signupLink: '회원가입',
    loginLink: '로그인',
    logoutBtn: '로그아웃',
    signupSuccess: '계정이 생성되었습니다! 이메일에서 확인 링크를 확인해주세요.',
    authRequired: '스타일 분석을 진행하려면 로그인해주세요.',
    forgotPassword: '비밀번호를 잊으셨나요?',
    forgotPasswordTitle: '비밀번호 찾기',
    forgotPasswordDesc: '가입한 이메일 주소를 입력해주세요. 비밀번호 재설정 링크를 보내드립니다.',
    forgotPasswordBtn: '재설정 이메일 전송',
    forgotPasswordSending: '전송 중...',
    forgotPasswordSent: '비밀번호 재설정 이메일을 전송했습니다! 이메일함을 확인하고 링크를 클릭해 새 비밀번호를 설정해주세요.',
    backToLogin: '\u2190 로그인으로 돌아가기',
    resetPasswordTitle: '새 비밀번호 설정',
    resetPasswordDesc: '새로 사용할 비밀번호를 입력해주세요.',
    resetPasswordBtn: '비밀번호 변경',
    resetPasswordSuccess: '비밀번호가 변경되었습니다! 홈으로 이동합니다...',
    errorPasswordMismatch: '비밀번호가 일치하지 않습니다.',
    errorInvalidEmail: '유효한 이메일 주소를 입력해주세요.',
    errorPasswordTooShort: '비밀번호는 8자 이상이어야 합니다.',
    errorPasswordWeak: '비밀번호에 대문자, 소문자, 숫자, 특수문자가 모두 포함되어야 합니다.',
    errorAuthGeneric: '인증 오류가 발생했습니다.',

    // Errors (client-side)
    errorAnalysis: '분석 중 오류가 발생했습니다.',
    errorUnknown: '알 수 없는 오류가 발생했습니다.',
    errorCheckout: '결제 세션 생성에 실패했습니다.',
    errorPayment: '결제 처리 중 오류가 발생했습니다.',

    // My Page
    myPageLabel: '계정 관리',
    myPageTitle: '마이페이지',
    myPageEmail: '이메일',
    myPageProvider: '로그인 방법',
    myPageJoined: '가입일',
    myPageProviderEmail: '이메일',
    myPageProviderGoogle: 'Google',
    myPageProviderKakao: 'Kakao',
    myPagePasswordSection: '비밀번호 변경',
    myPageNewPassword: '새 비밀번호',
    myPageConfirmPassword: '새 비밀번호 확인',
    myPageSavePassword: '비밀번호 변경',
    myPageSavingPassword: '변경 중...',
    myPagePasswordSuccess: '비밀번호가 변경되었습니다.',
    myPageOAuthPasswordNote: '소셜 로그인 계정은 비밀번호 변경이 불가합니다.',
    myPageDangerZone: '위험 영역',
    myPageDeleteAccountDesc: '계정 및 관련된 모든 데이터를 영구적으로 삭제합니다. 이 작업은 되돌릴 수 없습니다.',
    myPageDeleteAccount: '계정 탈퇴',
    myPageDeleteConfirmTitle: '계정 탈퇴',
    myPageDeleteConfirmText: '이 작업은 영구적이며 되돌릴 수 없습니다. 모든 데이터가 삭제됩니다.',
    myPageDeleteConfirmBtn: '탈퇴하기',
    myPageDeletingAccount: '탈퇴 처리 중...',
    myPageDeleteCancel: '취소',
    myPageDeleteError: '계정 탈퇴에 실패했습니다. 고객 지원에 문의해 주세요.',

    // Subscription management
    myPageSubscriptionSection: '구독 관리',
    myPageSubscriptionActive: '구독 중',
    myPageSubscriptionCanceling: '기간 종료 후 해지 예정',
    myPageSubscriptionNone: '활성 구독 없음',
    myPageSubscriptionActiveDesc: '구독이 활성 상태입니다. 스타일 분석을 무제한으로 이용할 수 있습니다.',
    myPageSubscriptionCancelingDesc: '구독이 해지 예정입니다. 현재 결제 기간 종료 시까지 이용할 수 있습니다.',
    myPageCancelSubscription: '구독 취소',
    myPageCancelSubscriptionConfirmTitle: '구독을 취소할까요?',
    myPageCancelSubscriptionConfirmText: '현재 결제 기간이 끝날 때까지 서비스를 이용할 수 있습니다. 이후에는 스타일 분석 이용이 불가합니다.',
    myPageCancelSubscriptionConfirmBtn: '네, 취소할게요',
    myPageCancellingSubscription: '취소 중...',
    myPageKeepSubscription: '구독 유지',
    myPageCancelSubscriptionSuccess: '구독이 취소되었습니다. 결제 기간 종료 시까지 서비스를 계속 이용할 수 있습니다.',
    myPageCancelSubscriptionError: '구독 취소에 실패했습니다. 다시 시도해 주세요.',
  },
} as const satisfies Record<Locale, Record<string, string>>

export type TranslationKey = keyof (typeof translations)['en']
